import { PropsWithChildren } from 'react'

import type { Metadata } from 'next'
import { Nunito_Sans } from 'next/font/google'

import { twMerge } from 'tailwind-merge'

import '@code-hike/mdx/dist/index.css'
import '@/styles/main.css'

const NunitoSans = Nunito_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: PropsWithChildren) {
  const { children } = props
  return (
    <html lang="en" className="h-full">
      <body
        className={twMerge(
          NunitoSans.className,
          'flex h-full w-full flex-col antialiased'
        )}
      >
        {children}
      </body>
    </html>
  )
}
