import { PropsWithChildren } from 'react'

import type { Metadata } from 'next'
import { Plus_Jakarta_Sans } from 'next/font/google'

import { twMerge } from 'tailwind-merge'

import '@/styles/main.scss'

const PlusJakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: PropsWithChildren) {
  const { children } = props
  return (
    <html lang="en" className="h-full">
      <body
        className={twMerge(
          PlusJakartaSans.className,
          'flex h-full w-full flex-col bg-white text-black antialiased dark:bg-zinc-900 dark:text-white'
        )}
      >
        {children}
      </body>
    </html>
  )
}
